config/routes.rb
Rails.application.routes.draw do

  root 'static_controller#home'

  get '/about', to: 'static_controller#about'
  get '/portfolio', to: 'static_controller#portfolio'
  get '/contact', to: 'static_controller#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller_controller.rb
class StaticControllerController < ApplicationController

	def home
	end

	def about
	end

	def portfolio
	end

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_controller_helper.rb
module StaticControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaticPageWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">

	<header>

	<link>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "about", about_path %></li>
			<li><%= link_to "portfolio", portfolio_path %></li>
			<li><%= link_to "contact", contact_path %></li>
		</ul>
	</link>

</header>


<%= yield %>

</body>
</html>

app/views/static_controller/about.html.erb
<h2>about</h2>

app/views/static_controller/contact.html.erb
<h2>contact</h2>

app/views/static_controller/home.html.erb
<div class="main content">

	<div class= "content">

		<article class= "topnav">

		</article>

	</div>

</div>

app/views/static_controller/portfolio.html.erb
<h2>portfolio</h2>